name: hedieaty
description: "Gift Management System App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  flutter_animate: ^4.5.0
  animated_introduction: ^1.0.4
  shared_preferences: ^2.3.2
  badges: ^3.1.2
  fluttertoast: ^8.2.8
  bubble_navigation_bar: ^0.0.2
  flutter_staggered_animations: ^1.1.1
  settings_ui: ^2.0.2


  sqflite: ^2.4.1
  path: ^1.9.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1

  connectivity_plus: ^6.1.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  mobile_scanner: ^6.0.2
  image_picker: ^0.8.4

  googleapis: ^13.2.0
  http: ^1.2.2
  googleapis_auth : ^1.6.0
  cloud_firestore: ^5.5.1
  firebase_database: ^11.2.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  mockito: 5.4.4
  fake_async: 1.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_lints: ^4.0.0
  firebase_core:
  firebase_database:




flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/landing.png