// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbJjdArexEDjhQcAdjFRU_FtmEcZkfl28',
    appId: '1:373295830647:web:19d92e569efcd369461872',
    messagingSenderId: '373295830647',
    projectId: 'hedieaty-b98ec',
    authDomain: 'hedieaty-b98ec.firebaseapp.com',
    storageBucket: 'hedieaty-b98ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3XUqweh2SC4aY48lMLhNt-cs1r6-IUMM',
    appId: '1:373295830647:android:6404b520c7c52cf1461872',
    messagingSenderId: '373295830647',
    projectId: 'hedieaty-b98ec',
    storageBucket: 'hedieaty-b98ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOxthPpfD0LFqvJZ7l-HEVgj1WZM1W9Es',
    appId: '1:373295830647:ios:d694974bd0fb8541461872',
    messagingSenderId: '373295830647',
    projectId: 'hedieaty-b98ec',
    storageBucket: 'hedieaty-b98ec.firebasestorage.app',
    iosBundleId: 'com.hedieaty.hedieaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOxthPpfD0LFqvJZ7l-HEVgj1WZM1W9Es',
    appId: '1:373295830647:ios:d694974bd0fb8541461872',
    messagingSenderId: '373295830647',
    projectId: 'hedieaty-b98ec',
    storageBucket: 'hedieaty-b98ec.firebasestorage.app',
    iosBundleId: 'com.hedieaty.hedieaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbJjdArexEDjhQcAdjFRU_FtmEcZkfl28',
    appId: '1:373295830647:web:f07b98c28e7b7d76461872',
    messagingSenderId: '373295830647',
    projectId: 'hedieaty-b98ec',
    authDomain: 'hedieaty-b98ec.firebaseapp.com',
    storageBucket: 'hedieaty-b98ec.firebasestorage.app',
  );
}
